import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
const [input,out,transport]=process.argv.slice(2);
if(!input||!out||!transport||!path.isAbsolute(input)||!path.isAbsolute(out)||!path.isAbsolute(transport))throw Error('absolute roles required');
const {argvBudget}=await import(pathToFileURL(path.join(transport,'argv-budget.mjs')));
const helper=fs.readFileSync(path.join(transport,'review-opus5-v.mjs'),'utf8');
const start=helper.indexOf('? `Perform an independent completed static SOURCE AND EVIDENCE review');
const end=helper.indexOf('`\n  :',start);
if(start<0||end<0)throw Error('source framing unavailable');
const candidate=fs.readFileSync(input);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const digest=sha(candidate),nonce='00000000-0000-0000-0000-000000000000';
const template=helper.slice(start+3,end).replaceAll('\\n','\n');
const request=template.replaceAll('${nonce}',nonce).replaceAll('${digest}',digest).replace('${candidate.toString(\'utf8\')}',candidate.toString('utf8'));
const schema=JSON.stringify({type:'object',additionalProperties:false,properties:{nonce:{type:'string',const:nonce},candidate_sha256:{type:'string',const:digest},verdict:{type:'string',enum:['ACCEPT','REJECT']},findings:{type:'array',items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},blocking:{type:'boolean'},evidence:{type:'string'},remedy:{type:'string'}},required:['id','blocking','evidence','remedy']}},rationale:{type:'string'}},required:['nonce','candidate_sha256','verdict','findings','rationale']});
const model='claude-opus-5';
const argv=['--safe-mode','--restricted','--model',model,'--effort','high','--permission-mode','dontAsk','--tools','','--no-session-persistence','--strict-mcp-config','--mcp-config','{"mcpServers":{}}','--prompt-suggestions','false','--output-format','json','--json-schema',schema,'-p',request];
const executable=fs.realpathSync('/Users/mhedhli/.local/bin/claude');
const env=Object.fromEntries(['HOME','USER','LOGNAME','PATH','LANG'].filter(k=>process.env[k]!==undefined).map(k=>[k,process.env[k]]));
Object.assign(env,{TMPDIR:path.join(out,'tmp'),DISABLE_AUTOUPDATER:'1',CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:'1',ANTHROPIC_DEFAULT_HAIKU_MODEL:model});
const budget=argvBudget(executable,argv,env);
if(Buffer.byteLength(request)>900000||!budget.allowed)throw Error('source budget unavailable');
const padded=argv.map(value=>'a'.repeat(Buffer.byteLength(value)));
// Match total executable+argument bytes while keeping the argument count.
padded[0]+='a'.repeat(Math.max(0,Buffer.byteLength(executable)-Buffer.byteLength('/usr/bin/true')));
execFileSync('/usr/bin/true',padded,{env,timeout:10000,maxBuffer:1024});
const help=execFileSync(executable,['--safe-mode','--restricted','--help'],{env,timeout:10000,maxBuffer:65536}).toString();
for(const flag of ['--safe-mode','--restricted','--tools','--strict-mcp-config','--json-schema','--no-session-persistence'])if(!help.includes(flag))throw Error('required capability absent');
console.log(JSON.stringify({status:'SOURCE_FREE_PADDING_EXEC_PASS',packet_sha256:digest,request_bytes:Buffer.byteLength(request),argument_count:argv.length,argument_utf8_lengths:argv.map(value=>Buffer.byteLength(value)),budget,executable,executable_sha256:sha(fs.readFileSync(executable)),capabilities_sha256:sha(help),environment_keys:Object.keys(env).sort()}));
