#!/usr/bin/env python3
"""Generated collapsed-identity bridge contract. Do not edit."""
from __future__ import annotations

IDENTITY_INPUT_SCHEMA = 'pulsarmlx.f017.event06-v12-prompt-bound-identity-bridge-input/1.1.0'
IDENTITY_INPUT_FIELDS = ('schema', 'state', 'posture', 'authorization_id', 'package_attempt_id', 'primary_event_id', 'secondary_event_id', 'execution_plan_sha256', 'preparation_sha256', 'collapsed_go_sha256', 'authority_mode', 'prompt_repository_commit', 'prompt_repository_path', 'prompt_sha256', 'event_identity_plan_sha256', 'installed_authority_sha256', 'installation_receipt_sha256')
IDENTITY_INPUT_TYPES = {'schema': 'str', 'state': 'str', 'posture': 'str', 'authorization_id': 'typed_id', 'package_attempt_id': 'typed_id', 'primary_event_id': 'typed_id', 'secondary_event_id': 'typed_id', 'execution_plan_sha256': 'sha256', 'preparation_sha256': 'sha256', 'collapsed_go_sha256': 'sha256', 'authority_mode': 'str', 'prompt_repository_commit': 'git_object', 'prompt_repository_path': 'repository_path', 'prompt_sha256': 'sha256', 'event_identity_plan_sha256': 'sha256', 'installed_authority_sha256': 'sha256', 'installation_receipt_sha256': 'sha256'}
BRIDGE_SCHEMA = 'pulsarmlx.f017.event06-v12-to-v11-prompt-bound-numerical-authority-bridge/2.1.0'
BRIDGE_FIELDS = ('schema', 'state', 'identity_bridge_input_sha256', 'event_identity_plan_sha256', 'preparation_sha256', 'collapsed_go_sha256', 'authority_mode', 'authorization_id', 'package_attempt_id', 'primary_event_id', 'secondary_event_id', 'execution_plan_sha256', 'prompt_repository_commit', 'prompt_repository_path', 'prompt_sha256', 'installed_authority_sha256', 'installation_receipt_sha256', 'legacy_bridge_sha256')
BRIDGE_TYPES = {'schema': 'str', 'state': 'str', 'identity_bridge_input_sha256': 'sha256', 'event_identity_plan_sha256': 'sha256', 'preparation_sha256': 'sha256', 'collapsed_go_sha256': 'sha256', 'authority_mode': 'str', 'authorization_id': 'typed_id', 'package_attempt_id': 'typed_id', 'primary_event_id': 'typed_id', 'secondary_event_id': 'typed_id', 'execution_plan_sha256': 'sha256', 'prompt_repository_commit': 'git_object', 'prompt_repository_path': 'repository_path', 'prompt_sha256': 'sha256', 'installed_authority_sha256': 'sha256', 'installation_receipt_sha256': 'sha256', 'legacy_bridge_sha256': 'sha256'}
CONSUMER_VIEW_SCHEMA = 'pulsarmlx.f017.event06-v12-prompt-bound-consumer-view/2.1.0'
CONSUMER_VIEW_FIELDS = ('schema', 'role', 'bridge_sha256', 'legacy_view_sha256', 'identity_bridge_input_sha256', 'event_identity_plan_sha256', 'preparation_sha256', 'collapsed_go_sha256', 'authority_mode', 'authorization_id', 'package_attempt_id', 'consumer_event_id', 'prompt_repository_commit', 'prompt_repository_path', 'prompt_sha256')
CONSUMER_VIEW_TYPES = {'schema': 'str', 'role': 'str', 'bridge_sha256': 'sha256', 'legacy_view_sha256': 'sha256', 'identity_bridge_input_sha256': 'sha256', 'event_identity_plan_sha256': 'sha256', 'preparation_sha256': 'sha256', 'collapsed_go_sha256': 'sha256', 'authority_mode': 'str', 'authorization_id': 'typed_id', 'package_attempt_id': 'typed_id', 'consumer_event_id': 'typed_id', 'prompt_repository_commit': 'git_object', 'prompt_repository_path': 'repository_path', 'prompt_sha256': 'sha256'}
CONSUMER_ROLES = ('PRIMARY_NUMERICAL', 'PRIMARY_RESULT', 'SECONDARY_NUMERICAL', 'SECONDARY_RESULT', 'COMPARISON', 'RELEASE', 'ACCOUNTING', 'PACKAGE_TERMINAL')
ACCOUNTING_SCHEMA = 'pulsarmlx.f017.event06-v12-prompt-bound-accounting-closure/2.1.1'
ACCOUNTING_FIELDS = ('schema', 'bridge_sha256', 'legacy_accounting_binding_sha256', 'event_identity_plan_sha256', 'preparation_sha256', 'collapsed_go_sha256', 'authority_mode', 'prompt_repository_commit', 'prompt_repository_path', 'prompt_sha256', 'authorization_id', 'package_attempt_id', 'primary_event_id', 'secondary_event_id', 'installed_authority_sha256', 'installation_receipt_sha256', 'authorization_delta', 'package_delta', 'primary_delta', 'secondary_delta', 'historical_master_ledger', 'result')
ACCOUNTING_TYPES = {'schema': 'str', 'bridge_sha256': 'sha256', 'legacy_accounting_binding_sha256': 'sha256', 'event_identity_plan_sha256': 'sha256', 'preparation_sha256': 'sha256', 'collapsed_go_sha256': 'sha256', 'authority_mode': 'str', 'prompt_repository_commit': 'git_object', 'prompt_repository_path': 'repository_path', 'prompt_sha256': 'sha256', 'authorization_id': 'typed_id', 'package_attempt_id': 'typed_id', 'primary_event_id': 'typed_id', 'secondary_event_id': 'typed_id', 'installed_authority_sha256': 'sha256', 'installation_receipt_sha256': 'sha256', 'authorization_delta': 'non_boolean_integer', 'package_delta': 'non_boolean_integer', 'primary_delta': 'non_boolean_integer', 'secondary_delta': 'non_boolean_integer', 'historical_master_ledger': 'non_boolean_integer', 'result': 'str'}
PACKAGE_TERMINAL_SCHEMA = 'pulsarmlx.f017.event06-v12-prompt-bound-package-terminal/2.1.0'
PACKAGE_TERMINAL_FIELDS = ('schema', 'bridge_sha256', 'legacy_package_terminal_sha256', 'accounting_closure_sha256', 'event_identity_plan_sha256', 'preparation_sha256', 'collapsed_go_sha256', 'authority_mode', 'prompt_repository_commit', 'prompt_repository_path', 'prompt_sha256', 'package_attempt_id', 'result')
PACKAGE_TERMINAL_TYPES = {'schema': 'str', 'bridge_sha256': 'sha256', 'legacy_package_terminal_sha256': 'sha256', 'accounting_closure_sha256': 'sha256', 'event_identity_plan_sha256': 'sha256', 'preparation_sha256': 'sha256', 'collapsed_go_sha256': 'sha256', 'authority_mode': 'str', 'prompt_repository_commit': 'git_object', 'prompt_repository_path': 'repository_path', 'prompt_sha256': 'sha256', 'package_attempt_id': 'typed_id', 'result': 'str'}
SIGNATURE_GRAPH_NODES = ('RAW_HUMAN_GO_BYTES', 'LIVE_GO_ENVELOPE_V3', 'SEALED_PROMPT_BOUND_IDENTITY_PLAN_V2', 'LIVE_APPROVAL_V3', 'PREPARED_PRODUCTION_INSTALLATION_V3', 'FUTURE_GO_CAPABILITY_V3', 'DURABLE_PRODUCTION_INSTALLATION_V3', 'INSTALLED_V12_AUTHORITY', 'SEALED_PROMPT_BOUND_BRIDGE_INPUT', 'SUCCESSOR_NUMERICAL_BRIDGE', 'SUCCESSOR_FIXED_EVENT06_COORDINATOR', 'PACKAGE_START', 'V12_IDENTITY_AND_LEASES', 'PRIMARY_AND_SECONDARY_WRAPPERS', 'COMPARISON', 'RELEASE', 'ACCOUNTING', 'PACKAGE_TERMINAL')
SIGNATURE_GRAPH_EDGES = ('RAW_HUMAN_GO_BYTES->LIVE_GO_ENVELOPE_V3', 'LIVE_GO_ENVELOPE_V3->SEALED_PROMPT_BOUND_IDENTITY_PLAN_V2', 'SEALED_PROMPT_BOUND_IDENTITY_PLAN_V2->LIVE_APPROVAL_V3', 'LIVE_APPROVAL_V3->PREPARED_PRODUCTION_INSTALLATION_V3', 'PREPARED_PRODUCTION_INSTALLATION_V3->FUTURE_GO_CAPABILITY_V3', 'FUTURE_GO_CAPABILITY_V3->DURABLE_PRODUCTION_INSTALLATION_V3', 'DURABLE_PRODUCTION_INSTALLATION_V3->INSTALLED_V12_AUTHORITY', 'INSTALLED_V12_AUTHORITY->SEALED_PROMPT_BOUND_BRIDGE_INPUT', 'SEALED_PROMPT_BOUND_BRIDGE_INPUT->SUCCESSOR_NUMERICAL_BRIDGE', 'SUCCESSOR_NUMERICAL_BRIDGE->SUCCESSOR_FIXED_EVENT06_COORDINATOR', 'SUCCESSOR_FIXED_EVENT06_COORDINATOR->PACKAGE_START', 'PACKAGE_START->V12_IDENTITY_AND_LEASES', 'V12_IDENTITY_AND_LEASES->PRIMARY_AND_SECONDARY_WRAPPERS', 'PRIMARY_AND_SECONDARY_WRAPPERS->COMPARISON', 'COMPARISON->RELEASE', 'RELEASE->ACCOUNTING', 'ACCOUNTING->PACKAGE_TERMINAL')
DIGEST_EDGES = ('IDENTITY_PLAN->APPROVAL', 'IDENTITY_PLAN->CANDIDATE', 'IDENTITY_PLAN->PREPARATION_RECEIPT', 'IDENTITY_PLAN->INSTALLED_AUTHORITY', 'IDENTITY_PLAN->BRIDGE_INPUT', 'IDENTITY_PLAN->NUMERICAL_BRIDGE', 'IDENTITY_PLAN->PRIMARY_CONSUMER_VIEW', 'IDENTITY_PLAN->SECONDARY_CONSUMER_VIEW', 'IDENTITY_PLAN->COMPARISON_VIEW', 'IDENTITY_PLAN->RELEASE_VIEW', 'IDENTITY_PLAN->ACCOUNTING_CLOSURE', 'IDENTITY_PLAN->PACKAGE_TERMINAL')
STAGE_VOCABULARY = ('PREPARED', 'INSTALLED', 'PACKAGE_START_ELIGIBLE_DRY_STOP', 'PACKAGE_START', 'IDENTITY_TERMINAL', 'PRIMARY_RESULT_TERMINAL', 'SECONDARY_RESULT_TERMINAL', 'COMPARISON_TERMINAL', 'RELEASE_TERMINAL', 'ACCOUNTING_CLOSURE', 'PACKAGE_TERMINAL')
ACCOUNTING_UNITS = ('authorization', 'package', 'primary', 'secondary')
FAILURE_OUTCOMES = ('IDENTITY_INPUT_TYPE_MISMATCH', 'IDENTITY_PLAN_DIGEST_MISMATCH', 'PROMPT_BINDING_MISMATCH', 'INSTALLED_AUTHORITY_MISMATCH', 'EXECUTION_PLAN_MISMATCH', 'BRIDGE_INPUT_REPLAY', 'CONSUMER_VIEW_SPLICE', 'ACCOUNTING_CLOSURE_MISMATCH', 'PACKAGE_TERMINAL_MISMATCH')
