#!/usr/bin/env python3
"""Generate the Cycle-9 successor design for F017 Event-06 Sequence 5.

This module is deliberately design-only.  It never resolves a checkpoint root,
creates live authority, or performs numerical work.  Every generated byte is a
pure function of committed repository bytes and explicit arguments.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from copy import deepcopy
from pathlib import Path

from f017_canonical_serialization_v10 import canonical_bytes
import generate_f017_event06_sequence05_design_v8 as v8


ROOT = v8.ROOT
C = v8.C
E = v8.E
ROLES = v8.ROLES

READINESS = C / "f017-corrected-oracle-event06-readiness-consumer-interface-v10.json"
INSTALL = C / "f017-corrected-oracle-event06-live-installation-interface-v9.json"
MANIFEST = C / "f017-corrected-oracle-event06-readiness-authority-manifest-v8.json"
QUAL = C / "f017-event06-sequence05-qualification-role-requirements-v7.json"
SCHEMA = C / "f017-event06-sequence05-qualification-schema-authority-v3.json"
PROV = C / "f017-independent-review-transport-provenance-v6.json"
ALIAS = C / "f017-event06-sequence05-alias-axis-authority-v2.json"
DISPOSITION = C / "f017-event06-sequence05-advisory-disposition-vocabulary-v1.json"
GENERATOR_POLICY = C / "f017-event06-sequence05-generator-validation-policy-v1.json"
PREPARED = E / "f017-event06-v12-sequence05-readiness-authority-manifest-prepared-v5.json"
REPAIR_LEDGER = E / "f017-event06-v12-sequence05-cycle8-repair-ledger-v1.json"
ADVISORY_LEDGER = E / "f017-event06-v12-sequence05-advisory-disposition-ledger-v4.json"
FAILURE_MATRIX = E / "f017-event06-v12-sequence05-failure-matrix-v8.json"
STATE_MACHINE = E / "f017-event06-v12-sequence05-installation-state-machine-v8.json"
GRAPH8 = E / "f017-event06-v12-sequence05-cycle7-review-graph-correction-v1.json"
CLAIMS8 = E / "f017-event06-v12-sequence05-cycle7-review-claim-correction-v1.json"
GRAPH9 = E / "f017-event06-v12-sequence05-design-graph-state-v9.json"
CLAIMS9 = E / "f017-event06-v12-sequence05-design-claim-ledger-v9.json"

OPUS8 = E / "f017-event06-v12-sequence05-opus-design-cycle-08-exact-response.md"
AGY8 = E / "f017-event06-v12-sequence05-agy-design-cycle-08-exact-response.md"


def sha_raw(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def sha(path: Path) -> str:
    return sha_raw(path.read_bytes())


def load(path: Path) -> dict:
    value = json.loads(path.read_bytes())
    if not isinstance(value, dict):
        raise ValueError(f"not object: {path.relative_to(ROOT)}")
    return value


def git_raw(head: str, path: str) -> bytes:
    return subprocess.run(
        ["git", "show", f"{head}:{path}"], cwd=ROOT, check=True, capture_output=True
    ).stdout


def write(path: Path, value: object, check: bool) -> None:
    raw = canonical_bytes(value)
    if check:
        if not path.is_file() or path.read_bytes() != raw:
            raise SystemExit(f"drift: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(raw)


def build_provenance_contract() -> dict:
    fields = [
        "schema", "tool", "tool_version", "transport", "command",
        "requested_model", "provider_reported_model", "provider_session_metadata",
        "independent_attestation_source", "capture_source_semantics",
        "provider_timing_status", "provider_started_at_utc",
        "provider_completed_at_utc", "duration_seconds", "exit_status",
        "request_path", "request_sha256", "response_path", "response_sha256",
        "normalized_result_path", "normalized_result_sha256", "reviewed_commit",
        "reviewed_tree", "credentials_serialized", "result",
    ]
    return {
        "schema": "pulsarmlx.f017.independent-review-transport-provenance-contract/1.5.0",
        "instance_schema": "pulsarmlx.f017.independent-review-transport-provenance/1.1.0",
        "required_fields": fields,
        "required_field_count": len(fields),
        "unknown_fields_permitted": False,
        "field_types": {
            "schema": "string", "tool": "enum:agy|opus", "tool_version": "string",
            "transport": "string", "command": "string", "requested_model": "string",
            "provider_reported_model": "string", "provider_session_metadata": "string",
            "independent_attestation_source": "enum",
            "capture_source_semantics": "enum:RAW_PROVIDER_ENVELOPE_FIELDS_ONLY_NO_FILESYSTEM_TIMES",
            "provider_timing_status": "enum:AVAILABLE_FROM_PROVIDER_ENVELOPE|UNAVAILABLE_FROM_PROVIDER_ENVELOPE",
            "provider_started_at_utc": "rfc3339-string-or-null",
            "provider_completed_at_utc": "rfc3339-string-or-null",
            "duration_seconds": "nonnegative-number", "exit_status": "nonnegative-integer",
            "request_path": "repository-path", "request_sha256": "sha256",
            "response_path": "repository-path", "response_sha256": "sha256",
            "normalized_result_path": "repository-path", "normalized_result_sha256": "sha256",
            "reviewed_commit": "git-object", "reviewed_tree": "git-object",
            "credentials_serialized": "boolean", "result": "enum",
        },
        "provider_timing_rule": (
            "timestamps are populated only from explicit provider-envelope fields; otherwise both are null "
            "and provider_timing_status is UNAVAILABLE_FROM_PROVIDER_ENVELOPE"
        ),
        "filesystem_time_sources_forbidden": [
            "st_mtime", "st_ctime", "st_birthtime", "checkout_time", "current_clock",
            "process_start_time", "git_checkout_time",
        ],
        "raw_provider_envelope_required": True,
        "credentials_serialized": False,
    }


def build_schema_authority() -> dict:
    return {
        "schema": "pulsarmlx.f017.event06-sequence05-qualification-schema-authority/1.2.0",
        "qualification_schema": "pulsarmlx.f017.event06-sequence05-qualification-role-requirements/1.6.0",
        "readiness_schema": "pulsarmlx.f017.corrected-oracle-event06-readiness-consumer-interface/2.8.0",
        "installation_schema": "pulsarmlx.f017.corrected-oracle-event06-live-installation-interface/1.8.0",
        "artifact_schema_equality_required": True,
        "self_reference_permitted": False,
    }


def build_readiness() -> dict:
    value = deepcopy(load(v8.READINESS))
    value.update(
        schema=build_schema_authority()["readiness_schema"],
        manifest_contract=str(MANIFEST.relative_to(ROOT)),
        qualification_role_requirements=str(QUAL.relative_to(ROOT)),
        review_transport_provenance_contract=str(PROV.relative_to(ROOT)),
    )
    return value


def build_manifest() -> dict:
    value = deepcopy(load(v8.MANIFEST))
    value.update(
        schema="pulsarmlx.f017.corrected-oracle-event06-readiness-authority-manifest-contract/1.7.0",
        manifest_schema="pulsarmlx.f017.corrected-oracle-event06-readiness-authority-manifest/1.7.0",
        prepared_instance_schema="pulsarmlx.f017.corrected-oracle-event06-readiness-authority-manifest-prepared/1.4.0",
        prepared_instance_path=str(PREPARED.relative_to(ROOT)),
        reviewed_design_head_policy="review artifacts bind the exact reviewed head/tree; later evidence publication heads are separately named",
    )
    return value


def build_installation() -> dict:
    value = deepcopy(load(v8.INSTALL))
    value.update(
        schema=build_schema_authority()["installation_schema"],
        qualification_role_requirements=str(QUAL.relative_to(ROOT)),
        state_machine_contract=str(STATE_MACHINE.relative_to(ROOT)),
    )
    return value


def build_alias_authority() -> dict:
    semantic = [
        "duplicate_semantics", "unknown_aliases", "type_coercions",
        "path_substitutions", "sha_substitutions", "canonical_encoding",
    ]
    structural = ["top_level_field", "nested_object_field", "nested_array_record"]
    cases = [
        {"case_id": f"ALIAS-{family}-{location}", "semantic_family": family,
         "structural_location": location}
        for family in semantic for location in structural
    ]
    return {
        "schema": "pulsarmlx.f017.event06-sequence05-alias-axis-authority/1.1.0",
        "semantic_families": semantic,
        "semantic_family_count": len(semantic),
        "independent_structural_locations": structural,
        "structural_location_count": len(structural),
        "axis_namespaces_disjoint": not set(semantic).intersection(structural),
        "derivation": "cartesian_product(semantic_families,independent_structural_locations)",
        "cases": cases,
        "derived_case_count": len(cases),
        "duplicate_case_ids": 0,
    }


def build_disposition_vocabulary() -> dict:
    return {
        "schema": "pulsarmlx.f017.event06-sequence05-advisory-disposition-vocabulary/1.0.0",
        "closed_values": [
            "MECHANICALLY_RESOLVED_PENDING_INDEPENDENT_REVIEW",
            "INDEPENDENTLY_ACCEPTED",
            "REJECTED_RETAINED",
            "UNRESOLVED",
        ],
        "acceptance_value": "INDEPENDENTLY_ACCEPTED",
        "pre_review_value": "MECHANICALLY_RESOLVED_PENDING_INDEPENDENT_REVIEW",
        "row_support_required": True,
        "row_support_sha_required": True,
        "counter_derivation": "derive exclusively from exact rows",
    }


def build_generator_policy() -> dict:
    return {
        "schema": "pulsarmlx.f017.event06-sequence05-generator-validation-policy/1.0.0",
        "generator_path": str(Path(__file__).relative_to(ROOT)),
        "clean_clone_check_required": True,
        "different_filesystem_mtimes_required": True,
        "repetitions": 2,
        "working_tree_must_remain_clean": True,
        "filesystem_timestamps_as_authority": False,
        "registered_validator_predicate_required": True,
        "negative_mutation_required": True,
        "review_identity_policy": "EXACT_REVIEWED_HEAD_TREE_DISTINCT_FROM_LATER_EVIDENCE_PUBLICATION_HEAD_TREE",
        "review_request_must_bind_exact_head_tree": True,
        "normalized_result_must_bind_exact_head_tree": True,
    }


def _cycle7_normalized(tool: str) -> dict:
    return load(E / f"f017-event06-v12-sequence05-{tool}-design-cycle-07-normalized-result.json")


def build_cycle7_provenance(tool: str) -> dict:
    envelope_path = E / f"f017-event06-v12-sequence05-{tool}-design-cycle-07-provider-envelope.json"
    request_path = E / f"f017-event06-v12-sequence05-{tool}-design-cycle-07-request.md"
    response_path = E / f"f017-event06-v12-sequence05-{tool}-design-cycle-07-exact-response.md"
    normalized_path = E / f"f017-event06-v12-sequence05-{tool}-design-cycle-07-normalized-result.json"
    envelope = load(envelope_path)
    normalized = _cycle7_normalized(tool)
    duration = envelope.get("duration_seconds")
    if duration is None:
        duration = envelope.get("duration_api_ms", 0) / 1000
    if tool == "agy":
        version = "1.1.22"
        requested = "gemini-3.1-pro-high"
        provider_model = "UNAVAILABLE_FROM_PROVIDER_ENVELOPE"
        session = (
            f"conversation_id={envelope['conversation_id']};status={envelope['status']};"
            f"duration_seconds={duration};turns={envelope['num_turns']}"
        )
        source = "AGY_JSON_ENVELOPE_CONVERSATION_ID_STATUS_DURATION_USAGE"
    else:
        version = "2.1.235"
        requested = "claude-opus-5"
        provider_model = "claude-opus-5" if "claude-opus-5" in envelope.get("modelUsage", {}) else "UNAVAILABLE"
        session = (
            f"session_id={envelope['session_id']};subtype={envelope['subtype']};"
            f"terminal_reason={envelope['terminal_reason']};"
            f"permission_denials={len(envelope['permission_denials'])}"
        )
        source = "CLAUDE_JSON_ENVELOPE_SESSION_ID_CANONICAL_MODEL_STATUS_USAGE"
    return {
        "schema": build_provenance_contract()["instance_schema"],
        "tool": tool,
        "tool_version": version,
        "transport": "RAW_PROVIDER_JSON_ENVELOPE",
        "command": "detached read-only cycle-7 design review; exact request bytes SHA-bound",
        "requested_model": requested,
        "provider_reported_model": provider_model,
        "provider_session_metadata": session,
        "independent_attestation_source": source,
        "capture_source_semantics": "RAW_PROVIDER_ENVELOPE_FIELDS_ONLY_NO_FILESYSTEM_TIMES",
        "provider_timing_status": "UNAVAILABLE_FROM_PROVIDER_ENVELOPE",
        "provider_started_at_utc": None,
        "provider_completed_at_utc": None,
        "duration_seconds": duration,
        "exit_status": 0,
        "request_path": str(request_path.relative_to(ROOT)),
        "request_sha256": sha(request_path),
        "response_path": str(response_path.relative_to(ROOT)),
        "response_sha256": sha(response_path),
        "normalized_result_path": str(normalized_path.relative_to(ROOT)),
        "normalized_result_sha256": sha(normalized_path),
        "reviewed_commit": normalized["reviewed_commit"],
        "reviewed_tree": normalized["reviewed_tree"],
        "credentials_serialized": False,
        "result": "REJECT_REVIEW_BANKED",
    }


OPUS_ROWS = [
    ("C8-OPUS-B1", "BLOCKING", "provenance generation used filesystem mtime and was not reproducible", "provenance_cycle7"),
    ("C8-OPUS-B2", "BLOCKING", "schema externality omitted readiness and installation artifact equality", "schema_externality"),
    ("C8-OPUS-B3", "BLOCKING", "provenance validation read Cycle 6 instead of Cycle 7", "provenance_cycle7"),
    ("C8-OPUS-B4", "BLOCKING", "Cycle 7 graph and claim state contradicted the rejected reviews", "graph_claim_state"),
    ("C8-OPUS-B5", "BLOCKING", "qualification claimed complete validation despite open gaps", "qualification_truth"),
    ("C8-OPUS-R1", "REQUIRED", "advisory disposition semantics and support SHAs were unenforced", "advisory_support"),
    ("C8-OPUS-R2", "REQUIRED", "AST guard was not bound to live predicate registries", "ast_registry"),
    ("C8-OPUS-R3", "REQUIRED", "validator did not load-bearingly enforce clean-clone generator reproduction", "generator_reproducibility"),
    ("C8-OPUS-R4", "REQUIRED", "review evidence did not distinguish reviewed and publication heads", "review_head_identity"),
    ("C8-OPUS-R5", "REQUIRED", "alias and failure-matrix counts were decorative", "alias_axes"),
    ("C8-OPUS-A1", "ADVISORY", "generator check rewrote provenance in the as-found worktree", "generator_reproducibility"),
    ("C8-OPUS-A2", "ADVISORY", "provenance key census was nearly tautological", "provenance_contract"),
    ("C8-OPUS-A3", "ADVISORY", "an advisory row used the validator SHA as self-proof", "advisory_support"),
    ("C8-OPUS-U1", "UNRESOLVED", "instantiability required re-adjudication after enforcement repair", "prepared_manifest"),
    ("C8-OPUS-U2", "UNRESOLVED", "advisory disposition required row-derived re-adjudication", "advisory_support"),
]


def build_repair_ledger() -> dict:
    opus_sha = sha(OPUS8)
    agy_sha = sha(AGY8)
    rows = [
        {
            "finding_id": finding_id,
            "severity": severity,
            "finding_summary": summary,
            "source_response_path": str(OPUS8.relative_to(ROOT)),
            "source_response_sha256": opus_sha,
            "overlapping_agy_ids": {
                "C8-OPUS-B1": ["C8-F1"], "C8-OPUS-B2": ["C8-F2"],
                "C8-OPUS-B3": ["C8-F3"], "C8-OPUS-R1": ["C8-F4"],
            }.get(finding_id, []),
            "validator_predicate": predicate,
            "mechanical_disposition": "MECHANICALLY_CLOSED_PENDING_INDEPENDENT_REVIEW",
        }
        for finding_id, severity, summary, predicate in OPUS_ROWS
    ]
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-cycle8-repair-ledger/1.0.0",
        "opus_source_response_path": str(OPUS8.relative_to(ROOT)),
        "opus_source_response_sha256": opus_sha,
        "agy_source_response_path": str(AGY8.relative_to(ROOT)),
        "agy_source_response_sha256": agy_sha,
        "opus_row_count": len(rows),
        "agy_row_count": 4,
        "agy_overlap_map": {
            "C8-F1": "C8-OPUS-B1", "C8-F2": "C8-OPUS-B2",
            "C8-F3": "C8-OPUS-B3", "C8-F4": "C8-OPUS-R1",
        },
        "rows": rows,
        "mechanically_closed_rows": len(rows),
        "independently_accepted_rows": 0,
        "status": "MECHANICALLY_CLOSED_PENDING_INDEPENDENT_REVIEW",
    }


ADVISORY_ROWS = [
    ("cycle04", f"A{i}") for i in range(1, 7)
] + [("cycle05", f"A{i}") for i in range(1, 4)] + [("cycle08", f"A{i}") for i in range(1, 4)]


def advisory_support_path(cycle: str, finding: str) -> Path:
    return E / f"f017-event06-v12-sequence05-advisory-support-{cycle}-{finding.lower()}-v1.json"


def build_advisory_support(cycle: str, finding: str) -> dict:
    if cycle == "cycle08":
        source = OPUS8
        underlying = REPAIR_LEDGER
        claim = f"{cycle} {finding} is represented by its exact Cycle-8 repair-ledger row"
    elif cycle == "cycle05":
        source = E / "f017-event06-v12-sequence05-opus-design-cycle-05-exact-response.md"
        underlying = GENERATOR_POLICY if finding == "A1" else GRAPH8 if finding == "A2" else SCHEMA
        claim = f"{cycle} {finding} is supported by a non-validator successor authority"
    else:
        source = E / "f017-event06-v12-sequence05-agy-design-cycle-04-exact-response.md"
        underlying = [v8.NOACCESS, PROV, v8.NOACCESS, STATE_MACHINE, STATE_MACHINE, SCHEMA][int(finding[1:]) - 1]
        claim = f"{cycle} {finding} has finding-specific successor support"
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-advisory-support/1.0.0",
        "source_cycle": cycle,
        "finding_id": finding,
        "source_response_path": str(source.relative_to(ROOT)),
        "source_response_sha256": sha(source),
        "finding_specific_claim": claim,
        "support_authority_path": str(underlying.relative_to(ROOT)),
        "support_authority_sha256": sha_raw(canonical_bytes(ARTIFACT_BUILDERS[underlying]())) if underlying in ARTIFACT_BUILDERS else sha(underlying),
        "disposition": "MECHANICALLY_RESOLVED_PENDING_INDEPENDENT_REVIEW",
    }


def build_advisory_ledger() -> dict:
    vocabulary = build_disposition_vocabulary()
    rows = []
    for cycle, finding in ADVISORY_ROWS:
        path = advisory_support_path(cycle, finding)
        support = build_advisory_support(cycle, finding)
        rows.append({
            "source_cycle": cycle,
            "finding_id": finding,
            "disposition": vocabulary["pre_review_value"],
            "support_path": str(path.relative_to(ROOT)),
            "support_sha256": sha_raw(canonical_bytes(support)),
        })
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-advisory-disposition-ledger/1.3.0",
        "disposition_vocabulary_path": str(DISPOSITION.relative_to(ROOT)),
        "disposition_vocabulary_sha256": sha_raw(canonical_bytes(vocabulary)),
        "rows": rows,
        "row_count": len(rows),
        "mechanically_resolved_pending_review": sum(
            row["disposition"] == vocabulary["pre_review_value"] for row in rows
        ),
        "independently_accepted": sum(row["disposition"] == vocabulary["acceptance_value"] for row in rows),
        "unresolved": sum(row["disposition"] == "UNRESOLVED" for row in rows),
        "counters_derived_from_rows": True,
    }


def build_state_machine() -> dict:
    value = deepcopy(load(E / "f017-event06-v12-sequence05-installation-state-machine-v7.json"))
    value.update(
        schema="pulsarmlx.f017.event06-v12-sequence05-installation-state-machine/1.7.0",
        alias_axis_authority_path=str(ALIAS.relative_to(ROOT)),
        alias_axis_authority_sha256=sha_raw(canonical_bytes(build_alias_authority())),
        alias_structural_variants=build_alias_authority()["independent_structural_locations"],
    )
    return value


def build_failure_matrix() -> dict:
    readiness = build_readiness()
    alias = build_alias_authority()
    machine = build_state_machine()
    deletions = len(readiness["required_fields"])
    types = sum(len(items) for items in readiness["exact_types"].values())
    predicates = len(readiness["exact_predicates"])
    alias_count = len(alias["cases"])
    race_count = len(machine["race_mutation_families"]) * 10
    total = deletions + types + predicates + alias_count + race_count
    value = deepcopy(load(E / "f017-event06-v12-sequence05-failure-matrix-v7.json"))
    value.update(
        schema="pulsarmlx.f017.event06-v12-sequence05-failure-matrix/1.7.0",
        derivation={
            "readiness_deletions": deletions, "readiness_types": types,
            "acceptance_predicates": predicates,
            "alternate_encoding_alias_binding_floor": alias_count,
            "installation_and_race_floor": race_count, "total": total,
        },
        minimum_mutations=total,
        alias_family_derivation={
            "authority_path": str(ALIAS.relative_to(ROOT)),
            "authority_sha256": sha_raw(canonical_bytes(alias)),
            "semantic_families": alias["semantic_families"],
            "independent_structural_locations": alias["independent_structural_locations"],
            "axes_disjoint": alias["axis_namespaces_disjoint"],
            "total": alias_count,
        },
    )
    return value


def build_qualification() -> dict:
    value = deepcopy(load(v8.QUAL))
    schema = build_schema_authority()
    value.update(
        schema=schema["qualification_schema"],
        all_requirements_mechanically_validated=False,
        validation_gap_count=1,
        active_validation_gap_ids=["PENDING_CYCLE9_MECHANICAL_VALIDATION"],
        validation_state="PENDING_EXTERNAL_VALIDATOR_EXECUTION",
        validation_result_source="scripts/research/validate_f017_event06_sequence05_design_v6.py",
    )
    authority_path = str(SCHEMA.relative_to(ROOT))
    authority_sha = sha_raw(canonical_bytes(schema))
    value["roles"]["readiness_interface"] = {
        "schema_authority_path": authority_path,
        "schema_authority_sha256": authority_sha,
        "schema_authority_field": "readiness_schema",
        "artifact_path": str(READINESS.relative_to(ROOT)),
        "required": {"canonical_bytes_required": True},
    }
    value["roles"]["live_installation_interface"] = {
        "schema_authority_path": authority_path,
        "schema_authority_sha256": authority_sha,
        "schema_authority_field": "installation_schema",
        "artifact_path": str(INSTALL.relative_to(ROOT)),
        "required": {"durable_commit_authorized_in_sequence_5": False},
    }
    value["roles"]["qualification_role_requirements"] = {
        "external_schema_authority_path": authority_path,
        "external_schema_authority_sha256": authority_sha,
        "schema_authority_field": "qualification_schema",
        "artifact_path": str(QUAL.relative_to(ROOT)),
        "required_fields": ["schema", "role_scope", "roles", "role_count"],
    }
    value["roles"]["review_transport_provenance_contract"]["required"]["schema"] = build_provenance_contract()["schema"]
    value["roles"]["challenge_provenance"]["contract"] = str(PROV.relative_to(ROOT))
    value["roles"]["challenge_provenance"]["required_fields"] = build_provenance_contract()["required_fields"]
    value["roles"]["failure_qualification"]["minimums"]["mutation_cases"] = build_failure_matrix()["minimum_mutations"]
    return value


def build_graph8() -> dict:
    agy = _cycle7_normalized("agy")
    opus = _cycle7_normalized("opus")
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-design-graph-state/1.7.0",
        "review_cycle": 7,
        "agy": {
            "blocking": agy["blocking_findings"], "required": agy["required_findings"],
            "advisory": agy["advisory_findings"], "unresolved": agy["unresolved_claims"],
            "verdict": agy["verdict"],
        },
        "opus": {
            "blocking": opus["blocking_findings"], "required": opus["required_findings"],
            "advisory": opus["advisory_findings"], "unresolved": opus["unresolved_claims"],
            "verdict": opus["verdict"],
        },
        "running_nodes": 0,
        "status": "REJECTED",
        "supersedes_false_pending_projection": str((E / "f017-event06-v12-sequence05-design-graph-state-v7.json").relative_to(ROOT)),
    }


def build_claims8() -> dict:
    opus = _cycle7_normalized("opus")
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-design-claim-ledger/1.7.0",
        "review_cycle": 7,
        "challenged": opus["blocking_findings"] + opus["required_findings"],
        "advisory": opus["advisory_findings"],
        "unresolved": opus["unresolved_claims"],
        "independently_accepted": 0,
        "status": "REJECTED",
        "supersedes_false_pending_projection": str((E / "f017-event06-v12-sequence05-design-claim-ledger-v7.json").relative_to(ROOT)),
    }


def build_graph9() -> dict:
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-design-graph-state/1.8.0",
        "source_review_cycle": 8,
        "source_opus_counts": {"blocking": 5, "required": 5, "advisory": 3, "unresolved": 2},
        "source_agy_counts": {"blocking": 4, "required": 0, "advisory": 0, "unresolved": 0},
        "repair_rows": len(OPUS_ROWS),
        "mechanically_closed_rows": len(OPUS_ROWS),
        "independent_review_status": "PENDING",
        "running_nodes": 0,
        "status": "PENDING_INDEPENDENT_REVIEW",
    }


def build_claims9() -> dict:
    rows = build_repair_ledger()["rows"]
    return {
        "schema": "pulsarmlx.f017.event06-v12-sequence05-design-claim-ledger/1.8.0",
        "source_review_cycle": 8,
        "rows": [{"claim_id": row["finding_id"], "state": "MECHANICALLY_SUPPORTED_PENDING_INDEPENDENT_REVIEW"} for row in rows],
        "row_count": len(rows),
        "mechanically_supported": len(rows),
        "independently_accepted": 0,
        "prior_unresolved_claims": 2,
        "status": "PENDING_INDEPENDENT_REVIEW",
    }


def generator_predicate_no_filesystem_time() -> bool:
    contract = build_provenance_contract()
    return "st_mtime" in contract["filesystem_time_sources_forbidden"] and not build_generator_policy()["filesystem_timestamps_as_authority"]


def generator_predicate_alias_derivation() -> bool:
    authority = build_alias_authority()
    return authority["derived_case_count"] == authority["semantic_family_count"] * authority["structural_location_count"] == len(authority["cases"])


GENERATOR_PREDICATES = {
    "no_filesystem_time": generator_predicate_no_filesystem_time,
    "alias_derivation": generator_predicate_alias_derivation,
}


ARTIFACT_BUILDERS: dict[Path, object] = {}


def _register_builders() -> None:
    ARTIFACT_BUILDERS.update({
        READINESS: build_readiness,
        INSTALL: build_installation,
        MANIFEST: build_manifest,
        QUAL: build_qualification,
        SCHEMA: build_schema_authority,
        PROV: build_provenance_contract,
        ALIAS: build_alias_authority,
        DISPOSITION: build_disposition_vocabulary,
        GENERATOR_POLICY: build_generator_policy,
        E / "f017-event06-v12-sequence05-agy-design-cycle-07-provenance-v2.json": lambda: build_cycle7_provenance("agy"),
        E / "f017-event06-v12-sequence05-opus-design-cycle-07-provenance-v2.json": lambda: build_cycle7_provenance("opus"),
        REPAIR_LEDGER: build_repair_ledger,
        ADVISORY_LEDGER: build_advisory_ledger,
        FAILURE_MATRIX: build_failure_matrix,
        STATE_MACHINE: build_state_machine,
        GRAPH8: build_graph8,
        CLAIMS8: build_claims8,
        GRAPH9: build_graph9,
        CLAIMS9: build_claims9,
    })
    for cycle, finding in ADVISORY_ROWS:
        ARTIFACT_BUILDERS[advisory_support_path(cycle, finding)] = (
            lambda cycle=cycle, finding=finding: build_advisory_support(cycle, finding)
        )


_register_builders()


def artifacts() -> dict[Path, object]:
    return {path: builder() for path, builder in ARTIFACT_BUILDERS.items()}


def current_bindings() -> dict[str, Path]:
    value = v8.current_bindings()
    value.update(
        readiness_interface=READINESS,
        live_installation_interface=INSTALL,
        qualification_role_requirements=QUAL,
        review_transport_provenance_contract=PROV,
    )
    return value


def prepared(head: str) -> dict:
    tree = subprocess.run(
        ["git", "rev-parse", f"{head}^{{tree}}"], cwd=ROOT, check=True,
        capture_output=True, text=True,
    ).stdout.strip()
    qualification = build_qualification()
    future = set(qualification["future_output_roles"])
    bindings = {}
    for role in ROLES:
        if role in future:
            requirement = qualification["roles"][role]
            bindings[role] = {
                "binding_state": "UNBOUND_FUTURE",
                "required_schema": requirement["required_schema"],
                "availability_stage": requirement["availability_stage"],
            }
        else:
            path = str(current_bindings()[role].relative_to(ROOT))
            bindings[role] = {
                "binding_state": "CURRENT_DESIGN_AUTHORITY",
                "path": path,
                "sha256": sha_raw(git_raw(head, path)),
            }
    return {
        "schema": "pulsarmlx.f017.corrected-oracle-event06-readiness-authority-manifest-prepared/1.4.0",
        "purpose": "DESIGN_INSTANTIABILITY_ONLY_NOT_LIVE_READINESS_AUTHORITY",
        "implementation_head": head,
        "implementation_tree": tree,
        "roles": ROLES,
        "role_count": len(ROLES),
        "bindings": bindings,
        "binding_count": len(bindings),
        "unbound_future_roles": sorted(future),
        "validated_binding_count": len(ROLES) - len(future),
        "result": "PREPARED_INCOMPLETE",
        "final_acceptance_eligible": False,
        "live_authority": False,
        "checkpoint_root_resolved": False,
        "checkpoint_access": 0,
        "numerical_operations": 0,
        "event_06_executed": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--emit-prepared")
    args = parser.parse_args()
    if not all(predicate() for predicate in GENERATOR_PREDICATES.values()):
        raise SystemExit("generator predicate failure")
    for path, value in artifacts().items():
        write(path, value, args.check)
    if args.emit_prepared:
        write(PREPARED, prepared(args.emit_prepared), args.check)
    elif args.check and PREPARED.is_file():
        head = load(PREPARED)["implementation_head"]
        write(PREPARED, prepared(head), True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
